language: en

bot:
  token: "YOUR_BOT_TOKEN_HERE"
  username: "YourBotUsername"

auth:
  login: "admin"
  password: "12345"

forbidden_commands:
  - "stop"
  - "reload"
  - "op"
  - "deop"

log_lines: 20